#admins = list of users allowed to use EvalJS. They must also have permission evaljs.code and be an operator
#timeout = number of seconds of inactivity after which to expire the console
#enabledUntil allows you to ensure that EvalJS only works when you plan to use it, and not when your evil sibling gets on your computer while you're away.
#enabledUntilDateMode: Defines how to parse your enabledUntil
#  0 = DateFormat.getDateInstance()
#  1 = DateFormat.getDateTimeInstance()
#  2 = DateFormat.getTimeInstance()
#Set enabledUntil to a negative value to be always enabled
#alwaysAllowConsole allows console to use EvalJS even when it is disabled (by enabledUntil)
#showWelcome displays a helpful intorduction message when you enter the console
#tabComplete enables tab completion. Due to a Bukkit limitation, it may under certain circumstances attempt to tab complete a different plugin's conversation.
#reprompt enables reprompting. Setting this to false allows Rhino to perform optimization, and may improve the performance of your code.
#hideChat hides chat messages while you're in the console
alwaysAllowConsole: true
admins: ["Saposhiente"]
timeout: 300
enabledUntil: -1
enabledUntilDateMode: 0
showWelcome: true
tabComplete: true
reprompt: true
hideChat: false